# Generated by Django 5.0.6 on 2025-11-15 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eda_payload', models.JSONField(default=dict)),
                ('multivariate_payload', models.JSONField(default=dict)),
                ('ml_payload', models.JSONField(default=dict)),
                ('anomalies_payload', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='accounts.beat')),
                ('data_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='uploads.dataasset')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.district')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
